name: Mobile Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Mark as a pre-release? (true/false)'
        default: 'false'
        required: false

permissions:
  contents: write

env:
  TAG_NAME: nightly-${{ github.run_number }}

jobs:
  create-nightly-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create and push tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

  build:
    name: Build
    needs: create-nightly-tag
    uses: ./.github/workflows/mobile.yml
    with:
      buildFlags: officialBuild

  release-android:
    name: Release Android Build
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Android artifact
        uses: actions/download-artifact@main
        with:
          name: androidBuild
      - name: Upload Android Build to Release
        uses: svenstaro/upload-release-action@2.5.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          file: JSEngine-release.apk
          asset_name: FNF-JS-Engine-android.apk
          overwrite: false

  release-ios:
    name: Release iOS Build
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download iOS artifact
        uses: actions/download-artifact@main
        with:
          name: iOSBuild
      - name: Zip For Release
        run: zip -r JSEngine-iOS.zip JSEngine.ipa
      - name: Upload iOS Build to Release
        uses: svenstaro/upload-release-action@2.5.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          file: JSEngine-iOS.zip
          asset_name: FNF-JS-Engine-iOS.zip
          overwrite: false
