name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/main.yml
    with:
      buildFlags: officialBuild

  release-linux:
    name: Release linuxBuild
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@main
      with:
        path: build
        name: linuxBuild
    - name: Compress build
      run: |
        sudo apt-get install p7zip-full
        7z a -tzip build.zip -w ./build/.
    - name: Upload linuxBuild to release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: build.zip
        asset_name: FNF-JS-Engine-linux.zip
        overwrite: false

  release-windows:
    name: Release windowsBuild
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@main
      with:
        path: build
        name: windowsBuild
    - name: Compress build
      run: |
        sudo apt-get install p7zip-full
        7z a -tzip build.zip -w ./build/.
    - name: Upload windowsBuild to release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: build.zip
        asset_name: FNF-JS-Engine-windows.zip
        overwrite: false

  release-mac:
    name: Release macBuild
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Mac Intel artifact
      uses: actions/download-artifact@main
      with:
        path: build
        name: macBuild-intel
    - name: Compress build
      run: |
        sudo apt-get install p7zip-full
        7z a -tzip buildIntel.zip -w ./build/.
        rm -rf ./build
    - name: Download Mac ARM artifact
      uses: actions/download-artifact@main
      with:
        path: build
        name: macBuild-arm
    - name: Compress build
      run: |
        7z a -tzip buildARM.zip -w ./build/.
        rm -rf ./build
    - name: Upload macBuild-intel to release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: buildIntel.zip
        asset_name: FNF-JS-Engine-macOS-Intel.zip
        overwrite: false
    - name: Upload macBuild-arm to release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: buildARM.zip
        asset_name: FNF-JS-Engine-macOS-ARM.zip
        overwrite: false
